<a href="https://colab.research.google.com/github/dialejo/Numpyproject/blob/main/numpyproject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

ano_inicial = 2002
ano_final = 2102

np.arange(ano_inicial, ano_final + 1,4)

array([2002, 2006, 2010, 2014, 2018, 2022, 2026, 2030, 2034, 2038, 2042,
       2046, 2050, 2054, 2058, 2062, 2066, 2070, 2074, 2078, 2082, 2086,
       2090, 2094, 2098, 2102])

In [4]:
import numpy as np



In [1]:
url = 'https://gist.githubusercontent.com/ahcamachod/41b8a65c5e5b58125401deafb68af460/raw/f84320f69efa1cc3e86e1db054422cfa4869c63e/manzanas.csv'

In [5]:
#data tiene 3 años y 3 meses lo que son 87 meses se colo 87 +1 debido a la inclusividad
np.arange(1,88)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87])

In [7]:
datos = np.loadtxt(url,delimiter=',',usecols=np.arange(1,88,1))

 convertir una lista en un array Numpy:

In [8]:
import numpy as np

# crea una lista
lista = [1, 2, 3, 4, 5]

# convierte la lista en un array Numpy
array = np.array(lista)

print("Lista: ", lista)
print("Array: ", array)


Lista:  [1, 2, 3, 4, 5]
Array:  [1 2 3 4 5]


Centrándonos en la eficiencia, podemos comparar el tiempo necesario para realizar un cálculo utilizando listas y arrays.

In [9]:
import time

# crea una lista con 1000000 elementos
lista = list(range(1000000))

# convierte la lista en un array Numpy
array = np.array(lista)

# comienza a medir el tiempo para la operación con la lista
start_time = time.time()

# realiza la operación de elevar al cuadrado cada elemento de la lista
lista_cuadrado = [i**2 for i in lista]

# detiene el cronómetro
tiempo_lista = time.time() - start_time

# comienza a medir el tiempo para la operación con el array
start_time = time.time()

# realiza la operación de elevar al cuadrado cada elemento del array
array_cuadrado = array**2

# detiene el cronómetro
tiempo_array = time.time() - start_time

print("Tiempo de la operación con la lista: ", tiempo_lista)
print("Tiempo de la operación con el array: ", tiempo_array)


Tiempo de la operación con la lista:  0.07177138328552246
Tiempo de la operación con el array:  0.0038428306579589844


#Métodos básicos para explorar Arrays

In [10]:
datos.ndim

2

In [11]:
datos.shape

(6, 87)

visualizacion mas facil:

In [13]:
datos_transpuestos = datos.T

In [14]:
datos_transpuestos

array([[  1.2013,  79.72  ,  42.67  ,  62.55  ,  48.26  ,  71.25  ],
       [  2.2013,  81.08  ,  44.37  ,  62.73  ,  51.01  ,  71.35  ],
       [  3.2013,  79.68  ,  44.73  ,  63.43  ,  50.91  ,  70.9   ],
       [  4.2013,  79.8   ,  46.75  ,  63.83  ,  53.94  ,  71.92  ],
       [  5.2013,  80.63  ,      nan,  66.06  ,  61.27  ,  72.91  ],
       [  6.2013,  80.8   ,  51.59  ,  69.22  ,  65.44  ,  74.39  ],
       [  7.2013,  80.28  ,  57.8   ,  72.07  ,  56.51  ,  73.1   ],
       [  8.2013,  78.99  ,  62.14  ,  69.31  ,  53.    ,  70.24  ],
       [  9.2013,  76.77  ,  56.76  ,  65.18  ,  43.87  ,  69.12  ],
       [ 10.2013,  76.09  ,  50.85  ,  62.13  ,  42.12  ,  68.98  ],
       [ 11.2013,  76.36  ,  46.43  ,  64.17  ,  43.98  ,  68.58  ],
       [ 12.2013,  77.16  ,  46.73  ,  65.5   ,  44.66  ,  69.5   ],
       [  1.2014,  77.5   ,  45.85  ,  66.85  ,  47.73  ,  70.14  ],
       [  2.2014,  79.03  ,  49.25  ,  68.38  ,  52.31  ,  70.58  ],
       [  3.2014,  80.28  ,  48.14

In [28]:
url2 = "https://gist.githubusercontent.com/ahcamachod/9be09de793dc3bf1e6c3d98eb4e5b1ef/raw/21b85572693200040e11284ef6dcfc3457ec8e11/citrus.csv"
datos2 = np.loadtxt(url2,delimiter=',',skiprows=1,usecols=np.arange(1,6,1))
datos2

array([[  2.96,  86.76, 172.  ,  85.  ,   2.  ],
       [  3.91,  88.05, 166.  ,  78.  ,   3.  ],
       [  4.42,  95.17, 156.  ,  81.  ,   2.  ],
       ...,
       [ 15.59, 256.5 , 168.  ,  82.  ,  20.  ],
       [ 15.92, 260.14, 142.  ,  72.  ,  11.  ],
       [ 16.45, 261.51, 152.  ,  74.  ,   2.  ]])

In [29]:
datos2.ndim

2

In [30]:
datos2.shape

(10000, 5)

In [31]:
datos2_transpuestos = datos2.T
datos2_transpuestos

array([[  2.96,   3.91,   4.42, ...,  15.59,  15.92,  16.45],
       [ 86.76,  88.05,  95.17, ..., 256.5 , 260.14, 261.51],
       [172.  , 166.  , 156.  , ..., 168.  , 142.  , 152.  ],
       [ 85.  ,  78.  ,  81.  , ...,  82.  ,  72.  ,  74.  ],
       [  2.  ,   3.  ,   2.  , ...,  20.  ,  11.  ,   2.  ]])